const std = @import("std");

pub const event_types = [_][]const u8{
    "edge.session_start",
    "edge.session_exit",
    "edge.scenario_start",
    "edge.scenario_exit",
    "edge.environment_detected",
    "edge.capability_reported",
    "data.payload_classified",
    "data.payload_redacted",
    "data.egress_requested",
    "data.egress_allowed",
    "data.egress_denied",
    "data.egress_observed",
    "data.exfiltration_suspected",
    "data.endpoint_classified",
    "telemetry.channel_observed",
    "telemetry.channel_allowed",
    "telemetry.channel_denied",
    "link.endpoint_unexpected",
    "link.command_control_observed",
    "link.telemetry_observed",
    "vehicle.state_observed",
    "vehicle.state_stale",
    "vehicle.state_invalid",
    "vehicle.mode_observed",
    "vehicle.battery_observed",
    "vehicle.position_observed",
    "vehicle.command_requested",
    "vehicle.command_mapped",
    "vehicle.command_allowed",
    "vehicle.command_denied",
    "vehicle.command_observed",
    "vehicle.command_forwarded",
    "vehicle.command_blocked",
    "vehicle.command_approval_required",
    "vehicle.command_allowed_by_approval",
    "vehicle.command_denied_missing_approval",
    "operator.approval_requested",
    "operator.approval_granted",
    "operator.approval_denied",
    "operator.approval_expired",
    "operator.approval_revoked",
    "operator.approval_invalid",
    "operator.approval_used",
    "operator.ask_denied_noninteractive",
    "safety.geofence_violation",
    "safety.altitude_violation",
    "safety.velocity_violation",
    "safety.stale_state_denied",
    "safety.battery_constraint",
    "safety.mode_constraint",
    "safety.authority_constraint",
    "safety.evaluation_started",
    "safety.evaluation_completed",
    "safety.finding_created",
    "safety.command_risk_denied",
    "safety.mission_item_denied",
    "emergency.evaluation_started",
    "emergency.evaluation_completed",
    "emergency.fallback_recommended",
    "emergency.command_allowed",
    "emergency.command_denied",
    "emergency.land_allowed",
    "emergency.return_home_allowed",
    "adapter.message_received",
    "adapter.message_forwarded",
    "adapter.message_denied",
    "mavlink.frame_received",
    "mavlink.frame_invalid",
    "mavlink.message_classified",
    "mavlink.command_mapped",
    "mavlink.command_allowed",
    "mavlink.command_denied",
    "mavlink.command_observed",
    "mavlink.message_forwarded",
    "mavlink.message_blocked",
    "mavlink.mission_upload_started",
    "mavlink.mission_item_observed",
    "mavlink.mission_item_denied",
    "mavlink.mission_upload_completed",
    "mavlink.signing_detected",
    "mavlink.unexpected_endpoint",
    "px4.sitl_detected",
    "px4.scenario_started",
    "px4.scenario_completed",
    "ardupilot.sitl_detected",
    "ardupilot.scenario_started",
    "ardupilot.scenario_completed",
    "safety_case.generated",
    "safety_case.limitation_recorded",
    "safety_case.evidence_collected",
    "safety_case.validation_failed",
    "health.watchdog.finding",
    "health.check_started",
    "health.check_completed",
    "health.status_changed",
    "health.heartbeat_observed",
    "health.heartbeat_expired",
    "health.state_stale",
    "health.state_expired",
    "health.command_timeout",
    "health.command_queue_overflow",
    "health.adapter_degraded",
    "health.link_degraded",
    "health.heartbeat.stale",
    "health.audit.failure",
    "health.audit_writer_failed",
    "health.redaction_failed",
    "health.policy_reload_failed",
    "health.runtime_asset_missing",
    "health.fallback_recommended",
    "health.no_safe_fallback",
    "health.command_denied",
};

pub const EdgeEventV1 = struct {
    version: u32 = 1,
    event_type: []const u8,
    timestamp_ms: i128,
    vehicle_id: ?[]const u8 = null,
    correlation_id: ?[]const u8 = null,

    pub fn validate(self: EdgeEventV1) !void {
        if (self.version != 1) return error.UnsupportedSchemaVersion;
        if (!hasEventType(self.event_type)) return error.UnknownEdgeEventType;
        if (self.timestamp_ms == 0) return error.MissingTimestamp;
    }
};

pub fn hasEventType(value: []const u8) bool {
    for (event_types) |event_type| {
        if (std.mem.eql(u8, event_type, value)) return true;
    }
    return false;
}
