pub const MAV_CMD_NAV_WAYPOINT: u16 = 16;
pub const MAV_CMD_NAV_LOITER_UNLIM: u16 = 17;
pub const MAV_CMD_NAV_RETURN_TO_LAUNCH: u16 = 20;
pub const MAV_CMD_NAV_LAND: u16 = 21;
pub const MAV_CMD_NAV_TAKEOFF: u16 = 22;
pub const MAV_CMD_DO_SET_MODE: u16 = 176;
pub const MAV_CMD_DO_SET_SERVO: u16 = 183;
pub const MAV_CMD_DO_SET_ACTUATOR: u16 = 187;
pub const MAV_CMD_DO_PAUSE_CONTINUE: u16 = 193;
pub const MAV_CMD_COMPONENT_ARM_DISARM: u16 = 400;
pub const MAV_CMD_MISSION_START: u16 = 300;
pub const MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN: u16 = 246;
pub const MAV_CMD_DO_GRIPPER: u16 = 211;
pub const MAV_CMD_PAYLOAD_PREPARE_DEPLOY: u16 = 30001;
pub const MAV_CMD_PAYLOAD_CONTROL_DEPLOY: u16 = 30002;

pub fn nameFor(command: u16) []const u8 {
    return switch (command) {
        MAV_CMD_NAV_WAYPOINT => "MAV_CMD_NAV_WAYPOINT",
        MAV_CMD_NAV_LOITER_UNLIM => "MAV_CMD_NAV_LOITER_UNLIM",
        MAV_CMD_NAV_RETURN_TO_LAUNCH => "MAV_CMD_NAV_RETURN_TO_LAUNCH",
        MAV_CMD_NAV_LAND => "MAV_CMD_NAV_LAND",
        MAV_CMD_NAV_TAKEOFF => "MAV_CMD_NAV_TAKEOFF",
        MAV_CMD_DO_SET_MODE => "MAV_CMD_DO_SET_MODE",
        MAV_CMD_DO_SET_SERVO => "MAV_CMD_DO_SET_SERVO",
        MAV_CMD_DO_SET_ACTUATOR => "MAV_CMD_DO_SET_ACTUATOR",
        MAV_CMD_DO_PAUSE_CONTINUE => "MAV_CMD_DO_PAUSE_CONTINUE",
        MAV_CMD_COMPONENT_ARM_DISARM => "MAV_CMD_COMPONENT_ARM_DISARM",
        MAV_CMD_MISSION_START => "MAV_CMD_MISSION_START",
        MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN => "MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN",
        MAV_CMD_DO_GRIPPER => "MAV_CMD_DO_GRIPPER",
        MAV_CMD_PAYLOAD_PREPARE_DEPLOY => "MAV_CMD_PAYLOAD_PREPARE_DEPLOY",
        MAV_CMD_PAYLOAD_CONTROL_DEPLOY => "MAV_CMD_PAYLOAD_CONTROL_DEPLOY",
        else => "UNKNOWN_MAV_CMD",
    };
}
